### ISSUE TITLE
Hide credentials form after logging in

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#11]
After clicking on “save”, credentials address and password still stays there and there is no user feedback that let the user know if the login worked correctly or not. We should have a message that says "logged in correctly" and then hide that form. The user should still be able to re-open that form to log in with a different user or logout.

**Comment by aquiladev** [comment]
right now login executes each request to MythX, that is why I used button `Save` for user credentials, not `Login`. User has a message about wrong credentials when he presses `Analyze` button.

It is possible to store JWT in local storage after the first login, it will slightly more complicated to handle

**Comment by aquiladev** [comment]
in scope of https://github.com/aquiladev/remix-mythx-plugin/pull/22 I implemented collapsing/expanding of credentials block

**Comment by aquiladev** [comment]
> request to add the text “hide” next to  icon V

![Annotation 2019-07-15 162243](https://user-images.githubusercontent.com/1164492/61223664-6b717a80-a71d-11e9-8f36-ac394f59c8da.png)

![Annotation 2019-07-15 162300](https://user-images.githubusercontent.com/1164492/61223672-6dd3d480-a71d-11e9-8537-d6762c0565bd.png)
