### ISSUE TITLE
Don't show warning message if contract was already compiled.

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#12]
On first instance of the plugin it stills shows “You must compile first” even though the user has already compiled the contract 
You can reproduce the above behaviour by: 

1. Open an incognito window 
2. Go to remix 
3. First enable the Solidity Compiler plugin
4. Compile contracts
5. Enable MythX

**Comment by yann300** [comment]
calling the remix-plugin method `getCompilationResult` when plugin loads should fix the issue...
@GrandSchtroumpf
