### ISSUE TITLE
Have an easy way to go back to plugin main page

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#14]
Analysis results currently open in the side-bar frame where plugin is and clicking the MythX logo just shows/hide sidebar does not redirect to plugin settings.

![image](https://user-images.githubusercontent.com/5368363/60188419-272e4100-9827-11e9-8eca-62505052614a.png)

**Comment by yann300** [comment]
I suppose that should involve some changes in remix-plugin (should open a new tab instead).
cc @GrandSchtroumpf
