### ISSUE TITLE
Keep contract in memory when clicking on back button

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#15]
If user clicks on browser back button this sends back user to plugin settings, but then contract dropdown disappears even though contract is still compiled.

**Comment by aquiladev** [comment]
It should not be possible to open any links in the plugin's iframe, it brakes flow, not user-friendly. I think we need to allow to open new tabs from a plugin's iframe. This issue will not be relevant when we solve an issue with opening a new tab.

related #14 #6
