### ISSUE TITLE
Add maximum time info under spinner

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#17]
After user click on analyse it would be nice to see a message that says "we are analysing  your contract. This should take up to X minutes" where X is the number of minutes the analysis process should take from the backend. 
This will be a bit more user friendly as the user will know that is not a very fast process the analysis.

**Comment by aquiladev** [comment]
is there a way to define timeouts in `mythxjs`?

**Comment by aquiladev** [comment]
[Discord discussion](https://discordapp.com/channels/481002907366588416/559709824942604293):
```
sergii.bomko 07-01-19 at 3:03 PM
Sometimes I face an issue that request to MythX API hangs forever, it hangs the whole app. Are there any plans to add timeouts for analysis request?

Nathan 07-01-19 at 3:48 PM
@sergii.bomko There is not currently a way to add timeouts, but there are now plans to do so, hopefully it will get implemented soon. :slight_smile:
```

**Comment by aquiladev** [comment]
there is a separate icon with tooltip 'we are analyzing your contract. This should take up to 2 minutes' while analyzing

**Comment by aquiladev** [comment]
> Request to show test on how long analysis will take instead of the button.

Options:

![Annotation 2019-07-15 161019](https://user-images.githubusercontent.com/1164492/61223917-e76bc280-a71d-11e9-9c5e-84643117a41f.png)

![Annotation 2019-07-15 161256](https://user-images.githubusercontent.com/1164492/61223927-ea66b300-a71d-11e9-9de6-b0b53010844f.png)
