### ISSUE TITLE
Submit ASTs instead of sources

### ISSUE THREAD

**Issue by b-mueller** [aquiladev/remix-mythx-plugin#3]
## Description

MythX works more reliably based on ASTs and use of source code will be deprecated shortly.  

Submit ASTs instead of sources in the `sources` dict of the request data. For an example how to construct a request with ASTs see:

https://github.com/b-mueller/sabre/blob/9ceb49218645cbcf700f4eea708a958ad306e16b/lib/client.js#L7

**Comment by aquiladev** [comment]
I'll take a look

**Comment by yann300** [comment]
we pushed a PR https://github.com/ethereum/remix/pull/1236,  in remix-alpha probably tomorrow (Tuesday)

**Comment by yann300** [comment]
I think the fix should already be in remix-alpha...

**Comment by aquiladev** [comment]
@yann300 I checked today, still `ast` is not there. I checked both environments, `remix` and `remix-alpha`

**Comment by yann300** [comment]
and now? (we just updated a few hours ago)

**Comment by aquiladev** [comment]
yes `remix-alpha` has `ast`

**Comment by aquiladev** [comment]
when AST is present, plugin uses it, otherwise it uses source
