### ISSUE TITLE
Add "clear" button next to contracts dropdown list.

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#31]
At the moment if the users compiles multiple contracts they all get added to the dropdown. This becomes unfriendly if there is a big number of contracts in memory, so we would like a clear button that resets that dropdown list.

**Comment by aquiladev** [comment]
![image](https://user-images.githubusercontent.com/1164492/61227152-0d946100-a724-11e9-9bb1-b16f573c992e.png)
