### ISSUE TITLE
Ability to run full mode

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#36]
We want to give users the ability to run full mode.

We do not want to show the results on the remix editor itself since these takes 30 minutes+, but rather have a button that says "Run full mode".
Once user clicks on it create a new request, this should be as easy as changing the request object from `quick` to `full`, and show an info box that says :
`Your analysis has been submitted! Please see your results at https://dashboard.mythx.io/#/console/analyses/${uuid}`

**Comment by aquiladev** [comment]
@Gtonizuka do you mean something like
![image](https://user-images.githubusercontent.com/1164492/66459493-c47f4f00-ea7d-11e9-913c-bd66b2bcc90b.png)

**Comment by aquiladev** [comment]
@Gtonizuka cant test full mode
`403 Full Mode is only available to pro users`
I use `0xE43DF5d7242ea18A8085fEecE9E479176a9350fD` account

**Comment by Gtonizuka** [comment]
you should be pro user now

**Comment by aquiladev** [comment]
@Gtonizuka 
Released https://github.com/aquiladev/remix-mythx-plugin/releases/tag/0.2.0
In order to test it, you need to connect local plugin http://remythx.xyz

**Comment by aquiladev** [comment]
@Gtonizuka let me know if you have any comments, otherwise, I will ask Remix team to upgrade plugin

**Comment by aquiladev** [comment]
version 0.2.0 deployed
