### ISSUE TITLE
MythX icon not showing in Remix

### ISSUE THREAD

**Issue by b-mueller** [aquiladev/remix-mythx-plugin#4]
## Description

When adding the MythX plugin via "Connect to a local plugin" (https://remythx.xyz), the default smiley icon is displayed in the sidebar instead of the MythX icon. This happens both in Chrome and Safari in the sidebar and code editor tab.

<img width="370" alt="Screen Shot 2019-05-31 at 17 33 56" src="https://user-images.githubusercontent.com/5194767/58718224-5f2f9900-83cd-11e9-84bd-04827f5aecb2.png">

## Expected behavior

The sidebar and code editor tab should show the MythX icon.

**Comment by b-mueller** [comment]
Ok, this will probably be solved once the plugin is built into Remix...

**Comment by aquiladev** [comment]
yes, it requires definition:
https://github.com/ethereum/remix-ide/pull/1999/files#diff-8adf04c5a6537319153b09ecbbb10fa4R113
So for local plugins, I think it is not possible to define, I've connected a couple of plugins locally, all have smile icon.
