### ISSUE TITLE
Getting `Error 400: Invalid bytecode`

### ISSUE THREAD

**Issue by Gtonizuka** [aquiladev/remix-mythx-plugin#40]
In contracts with imports it seems that the plugin is failing to resolve them. Its likely that you are not resolving the placeholders (https://solidity.readthedocs.io/en/v0.5.12/contracts.html)

Give me a shout if you need extra info.

Test case: 

https://github.com/b-mueller/sabre/blob/master/contracts/MetaCoin.sol

**Comment by aquiladev** [comment]
fixes cf0c295
