### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by bunsenstraat** [aquiladev/remix-mythx-plugin#51]
Hi we're having trouble with our IPFS host. It'd be better if you put it somewhere else if you can. For now until we find a solution.

**Comment by aquiladev** [comment]
ok, I'll take a look

**Comment by aquiladev** [comment]
you can use https://cloudflare-ipfs.com/ipfs/Qmdfrs8Cdak7dZFveeXEX8ikBqXRoePFfnPMwbr3wx29p4/
the version was increased to 0.3.7 due to security updates

**Comment by aquiladev** [comment]
@bunsenstraat any news so far? it looks like it still does not work on prod

**Comment by bunsenstraat** [comment]
It's there, it's live already. What is the issue?

**Comment by aquiladev** [comment]
it works, thanks
