### ISSUE TITLE
Open SWC link in new tab

### ISSUE THREAD

**Issue by b-mueller** [aquiladev/remix-mythx-plugin#6]
Currently, when the user clicks on the SWC link the SWC page opens in the current window (i.e. replaces the Remix sidebar. I suggest opening a new tab instead.

**Comment by aquiladev** [comment]
it is a known issue. the problem in `iframe`, there is no way to open an external link from the iframe in new tab. I'm working with Remix team to solve it.

**Comment by yann300** [comment]
quite the same as https://github.com/aquiladev/remix-mythx-plugin/issues/14 i  guess

**Comment by aquiladev** [comment]
I think `remix-plugin` should make it possible to open a new tab from the plugin's iframe

**Comment by aquiladev** [comment]
https://github.com/ethereum/remix-plugin/issues/105
